### ISSUE TITLE
bug: part highlight does not refresh when the board is dragged/moved

### ISSUE THREAD

**Issue by smonk** [oceanofthelost/InteractivePCB#101]
hello

I have been trying the latest version out today and it is great. thank you for continuing to develop this tool.

I have noticed 1 small bug which is probably easy to fix. 

How to create the bug:

1) Highlight a single part on the board either by clicking on an element in the  BOM or on the Board view. Make sure a square/highlight appears on a part. 

2) Move the mouse over the board view and left click + drag to move the board.  Release the left mouse button to finish the drag move. The board is repositioned as expected.

The bug: When you look at the board view the part chosen in step 1 is no longer highlighted. However, it is highlighted in the BOM still, and if you zoom in or out using the mouse wheel the highlight on the board actually comes back without clicking anything. So i think it is just something with how the board refreshes after a drag move.

Thanks!

**Comment by oceanofthelost** [comment]
Issue seams to stem from the selected part highlight not being called when redrawing the canvas. 

Can reproduce and will introduce a fix in the next release.
