### ISSUE TITLE
Remove BOM Entries does not filter references

### ISSUE THREAD

**Issue by Yourigh** [oceanofthelost/InteractivePCB#103]
BOM entries C1 and C2 does not disappear when I enter "C1,C2" to Remove BOM Entries field. 

This can be hacked by adding "NAME" to Additional Attributes field. Then the references are recognized and removed.

options how to fix:
* add to documentation how this feature should work (maybe also with NAME workaround)
* make it work for filtering references (if it was intended)

**Comment by oceanofthelost** [comment]
Fixed in V3 and added to next release.
