### ISSUE TITLE
GUI not working - missing file "index.js"?

### ISSUE THREAD

**Issue by zchris9** [oceanofthelost/InteractivePCB#109]
The GUI does not work on Firefox and Chrome. Is the file "index.js", which is loaded in line 171 of iPCB.html [1], needed? Maybe it was not added to the commit? I tried with the index.js from the 1.6 release [2] and it does not work.

[1] https://github.com/oceanofthelost/InteractivePCB/blob/master/GUI/iPCB.html
[2] https://github.com/oceanofthelost/InteractivePCB/blob/d996daf358bb27a434af616e35d07ff04e1dda88/Release/V1_6.zip

**Comment by oceanofthelost** [comment]
"index.js" needs to be in the same folder as iPCB.html. 

index.js is a generated file and not committed. To download index.js, go to the [releases](https://github.com/oceanofthelost/InteractivePCB/releases) page and download the Zip file. 

V1.6 is quiet old. I would recommenced suing a V2.x release as these fix multiple bugs.

**Comment by zchris9** [comment]
yes, thank you, the file is present in the release zip file
