### ISSUE TITLE
Add Documentation

### ISSUE THREAD

**Issue by oceanofthelost** [oceanofthelost/InteractivePCB#18]
Currently there is no README or any documentation on how any of the program works. It will be useful for everyone if one was created.

**Comment by tablatronix** [comment]
hmm how does the filter and attributes fields work? I always forget, is it delimited , wildcards? regex?

**Comment by oceanofthelost** [comment]
Attribute properties are broken into two parts. Eagle exports the two ';' delimited lists. The first is attributes names, and the second is attributes values. 

these list are then read into pcb.js

https://github.com/oceanofthelost/InteractiveBOM/blob/e70603993a34e5a2570f58bcf404cf3e361e50a2/GUI/src/pcb.js#L58-L59

At this time split(';') converts the values from being ';' delimited  and generates an array of the values. 

It is assumed that ```attributeNames```  and ```attributeNames```  have the same number of items, if not then this would be an error. 

For example 
```'json
{"NAME;VALUE;","POWER;;"}
```

The first string represents attributeNames and the second string represents attributeNames. After calling split
```
attributeNames  = ["NAME", "VALUE"]
attributeValues = ["POWER", ""]
```

See Issue #27 , for more info on how filtering works.

**Comment by tablatronix** [comment]
- [ ] Add a placeholder or an example for filtering syntax

**Comment by oceanofthelost** [comment]
Information on removing BOM entry can be found in issue #69 as this fixed the feature not working.
