### ISSUE TITLE
'Combine Values' Not Combining All Parts In V2.0-RC1

### ISSUE THREAD

**Issue by zchris9** [oceanofthelost/InteractivePCB#46]
'Combine values' does not combine all parts with the same value if they are not in a single block of ordered reference designators. See figure:

![grafik](https://user-images.githubusercontent.com/38182669/103900403-0d4a0b80-50f8-11eb-8459-f1bb2eef007d.png)

**Comment by oceanofthelost** [comment]
Issue stems from 

```js
GetBOMCombinedValues()
```

This function assumes the BOM table is sorted when combining values. When items are not sorted the above behavior is seen. 

Fix will be to update function to first sort parts by value and then combine.

**Comment by oceanofthelost** [comment]
Resolved in V3. 

Sort is performed on part values and then displayed on BOM. Fix will not be back ported to V2.
