### ISSUE TITLE
Part Bounding Box Contains Value Extents

### ISSUE THREAD

**Issue by tablatronix** [oceanofthelost/InteractivePCB#61]
How can this be fixed, is this a limitation in the eagle ULP or eagle itself?

The parts highlights contain a bounding box coords defined by footprint and value, any way to fix this ?

![Screen Shot 2021-12-28 at 4 57 51 PM](https://user-images.githubusercontent.com/807787/147613210-df2e4d37-36ab-4e2c-83e6-6e504d755072.png)
![Screen Shot 2021-12-28 at 4 57 47 PM](https://user-images.githubusercontent.com/807787/147613216-a7f9f0dc-1b19-4f83-b44f-01ddf32dcd90.png)

**Comment by oceanofthelost** [comment]
Related to issue #28. Validate UL_AREA is being used correctly in ULP.

**Comment by oceanofthelost** [comment]
Code that calculates bounding box for part in ipcb.ulp

```c++
void PrintPackageBoundingBox(UL_ELEMENT E)
{
     PrintTabs();
    // Print the edge_box segment to the output file
    printf("\"bounding_box\":{");
    printf("\"x0\":%5.5f,", u2mm(E.package.area.x1));
    printf("\"y0\":%5.5f,", u2mm(E.package.area.y1));
    printf("\"x1\":%5.5f,", u2mm(E.package.area.x2));
    printf("\"y1\":%5.5f" , u2mm(E.package.area.y2));
    printf("},");
}
```

Will need to investigate why E.package.area is not giving correct bounding box.

**Comment by tablatronix** [comment]
Thanks, it looks like  
"UL_AREA is an abstract object" so it contains unsmashed (undetached) texts and values

Seems that in order to work around this, would require a bit of looping and dimensional math to either loop texts() and undimension them from area, or loop other objects and vice versa.. seems like a PITA..

**Comment by oceanofthelost** [comment]
From UL_Element, the center point for a part is given. 

Now the main challenge would be to iterate of UL_PACKAGE (sub-element of UL_ELEMENT) and find the actual width and length of the part. Then that data can be used along with the origin point to calculate the bounding box. 

Like you said it sounds like it will be a PITA. Its better than the original issue in #28 where the bounding box was smaller than the part.

**Comment by tablatronix** [comment]
Yeah but it has to be calculated from UL_FOOTPRINT (legacy UL_PACKAGE) now..

<h2 id="loop-members" style="color: rgb(60, 60, 60); margin: 30px 0px 15px; font-size: 18px; font-weight: 500; font-family: ArtifaktElement, Arial, Helvetica, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">Loop members</h2><div class="ui-table-wrap" style="overflow: auto; max-width: 100%; color: rgb(60, 60, 60); font-family: ArtifaktElement, Arial, Helvetica, sans-serif; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 500; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

  |  
-- | --
circles() | UL_CIRCLE
contacts() | UL_CONTACT
dimensions() | UL_DIMENSION
frames() | UL_FRAME
holes() | UL_HOLE
polycutouts() | UL_POLYCUTOUT
polyshapes() | UL_POLYSHAPE (see note)
rectangles() | UL_RECTANGLE
texts() | UL_TEXT (see note)
wires() | UL_WIRE (see note)

</div>
