### ISSUE TITLE
Option to Toggle layer panel off

### ISSUE THREAD

**Issue by tablatronix** [oceanofthelost/InteractivePCB#66]
Self explanatory.

**Comment by oceanofthelost** [comment]
Added to both V2 development (3f709a815c58171d9600805478cb402bf578ffdc) branch and V3 development branch (9be745dd535bc76ace970aa3c46bd35b9cf6b7be).

**Comment by oceanofthelost** [comment]
Added to release [V2.3.0](https://github.com/oceanofthelost/InteractivePCB/releases/tag/V2.3.0)
