### ISSUE TITLE
Option to disable attr columns

### ISSUE THREAD

**Issue by tablatronix** [oceanofthelost/InteractivePCB#67]
I think you can add attributes via the options to the table, but how can you remove stuff, for example the footprint column now..
Maybe use the same method to allow removal special syntax or escape wrap ? (_remove)

**Comment by oceanofthelost** [comment]
Commit 5ae172ed48bec65cc4d4b0daf2130b6fb1211b82 now allows user to specify if the footprint column should be shown. 

At a minimum, the only columns that cannot be removed are Value and Reference. Placed column is displayed by default but can be removed under the settings menu. 

@tablatronix, does 5ae172ed48bec65cc4d4b0daf2130b6fb1211b82 meet the intent of what you were looking for?

**Comment by oceanofthelost** [comment]
Added to release [V2.3.0](https://github.com/oceanofthelost/InteractivePCB/releases/tag/V2.3.0)
