### ISSUE TITLE
Allow Configuration Via Config File For Web UI

### ISSUE THREAD

**Issue by tablatronix** [oceanofthelost/InteractivePCB#77]
Allow configuring defaults via a config file or maybe querystring for all options.
dark mode, layers, layout etc

**Comment by oceanofthelost** [comment]
Config file groundwork is now defined starting with commit 0c474a0d936e153d46a9bd797b5e5e1a0fb54042. 

For in UI, issue #57 was created to address making is easier to adjust parameters within the UI.

**Comment by oceanofthelost** [comment]
Add following options to EagleULP

- [ ] dark mode
- [ ] highlight first pin
- [ ] combine values
- [ ] hide placed parts
- [ ] additional attributes
- [ ] bom & pcb layout
- [ ] pcb orientation
- [ ] table
